apiVersion: v1
kind: Secret

metadata:
  name: mortgage-secrets
  namespace: mortgagebank

type: Opaque

stringData:

  POSTGRES_USER:
    mortgage

  POSTGRES_PASSWORD:
    mortgagepass

  RABBITMQ_USER:
    mortgage

  RABBITMQ_PASSWORD:
    mortgagepass