server:
  port: 8080

spring:
  jpa:
    open-in-view: false

  application:
    name: mortgage-bank

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mortgagebank}
    username: ${SPRING_DATASOURCE_USERNAME:mortgage}
    password: ${SPRING_DATASOURCE_PASSWORD:mortgagepass}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:mortgage}
    password: ${SPRING_RABBITMQ_PASSWORD:mortgagepass}

management:

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

  endpoint:
    health:
      show-details: always