[mortgage_servers]

mortgage01 ansible_host=192.168.1.100

[mortgage_servers:vars]

ansible_user=azureuser

ansible_python_interpreter=/usr/bin/python3 

[production]
prod-node-1 ansible_host=192.168.1.100 ansible_user=ubuntu